# Generated by Django 2.1.5 on 2025-05-27 21:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.CharField(max_length=30)),
                ('fecha_estimada_salida', models.CharField(max_length=30)),
                ('examenes_ids', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
            ],
        ),
    ]
