# Generated by Django 2.1.5 on 2025-05-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='examenes_ids',
        ),
    ]
