# Generated by Django 2.1.5 on 2025-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0002_remove_usuario_examenes_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='examenes_ids',
            field=models.TextField(blank=True, default=''),
        ),
    ]
