# Generated by Django 4.2.21 on 2025-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0003_usuario_examenes_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
